language: php
php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

sudo: false

matrix:
  fast_finish: true

before_install:
    - if [[ $TRAVIS_PHP_VERSION != 'hhvm' ]]; then phpenv config-rm xdebug.ini; fi;
    - pip install --user codecov

before_script:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -ge 70000 ]]; then pecl config-set preferred_state beta; printf "yes\n" | pecl install apcu; else echo "extension=apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  # must be set after composer to avoid issue with autoloading
  - echo "apc.enable_cli=On" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

script:
    - php -dzend_extension=xdebug.so vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - codecov
